export const shipsData = [
  {
    name: '30 дивізія надводних кораблів',
    city: 'Севастополь',
    abbreviatedName: '30 днк',
    ships: [
      {
        name: 'Ладный',
        bortNumber: '861',
        project: '1135',
        type: 'сторожевий корабель',
        abbreviatedType: 'скр',
      },
      {
        name: 'Пытливый',
        bortNumber: '888',
        project: '1135М',
        type: 'сторожевий корабель',
        abbreviatedType: 'скр',
      },
      {
        name: 'Адмирал Григорович',
        bortNumber: '494',
        project: '11356Р',
        type: 'фрегат',
        abbreviatedType: 'фр',
      },
      {
        name: 'Адмирал Макаров',
        bortNumber: '499',
        project: '11356Р',
        type: 'фрегат',
        abbreviatedType: 'фр',
      },
      {
        name: 'Адмирал Эссен',
        bortNumber: '490',
        project: '11356Р',
        type: 'фрегат',
        abbreviatedType: 'фр',
      },
    ],
  },
  {
    name: '197 бригада десантних кораблів',
    city: 'Севастополь',
    abbreviatedName: '197 брдк',
    ships: [
      {
        name: 'Ямал',
        bortNumber: '156',
        project: '775',
        type: 'великий десантний корабель',
        abbreviatedType: 'вдк',
      },
      {
        name: 'Азов',
        bortNumber: '151',
        project: '775М',
        type: 'великий десантний корабель',
        abbreviatedType: 'вдк',
      },
      {
        name: 'Орск',
        bortNumber: '148',
        project: '1171',
        type: 'великий десантний корабель',
        abbreviatedType: 'вдк',
      },
      {
        name: 'Николай Фильченков',
        bortNumber: '152',
        project: '1171',
        type: 'великий десантний корабель',
        abbreviatedType: 'вдк',
      },
    ],
  },
  {
    name: '166 Новоросійський дивізіон малих ракетних кораблів',
    city: 'Севастополь',
    abbreviatedName: '166 днмрк',
    ships: [
      {
        name: 'Самум',
        bortNumber: '616',
        project: '1239',
        type: 'ракетний корабель на повітряній подушці',
        abbreviatedType: 'ркпп',
      },
      {
        name: 'Бора',
        bortNumber: '615',
        project: '1239',
        type: 'ракетний корабель на повітряній подушці',
        abbreviatedType: 'ркпп',
      },
      {
        name: 'Вышний Волочек',
        bortNumber: '609',
        project: '21631',
        type: 'малий ракетний корабель',
        abbreviatedType: 'мрк',
      },
      {
        name: 'Ингушетия',
        bortNumber: '630',
        project: '21631',
        type: 'малий ракетний корабель',
        abbreviatedType: 'мрк',
      },
      {
        name: 'Грайворон',
        bortNumber: '600',
        project: '21631',
        type: 'малий ракетний корабель',
        abbreviatedType: 'мрк',
      },
      {
        name: 'Орехово-Зуево',
        bortNumber: '626',
        project: '21631',
        type: 'малий ракетний корабель',
        abbreviatedType: 'мрк',
      },
    ],
  },
  {
    name: '41 бригада ракетних кораблів',
    city: 'Севастополь',
    abbreviatedName: '41 бррк',
    ships: [],
  },
  {
    name: '295 Сулінський дивізіон ракетних катерів',
    city: 'Севастополь',
    abbreviatedName: '41 сднрка',
    ships: [
      {
        name: 'Набережны Челны',
        bortNumber: '953 Р239',
        project: '1241.1',
        type: 'ракетний катер',
        abbreviatedType: 'рка',
      },
      {
        name: 'Р60',
        bortNumber: '955',
        project: '1241.1М',
        type: 'ракетний катер',
        abbreviatedType: 'рка',
      },
    ],
  },
  {
    name: '68 бригада кораблів охорони водного району',
    city: 'Севастополь',
    abbreviatedName: '68 брковр',
    ships: [],
  },
  {
    name: '149 протичовнова тактична група',
    city: 'Севастополь',
    abbreviatedName: '149 птг',
    ships: [
      {
        name: 'Александровец',
        bortNumber: '059',
        project: '1124',
        type: 'малий протичовновий корабель',
        abbreviatedType: 'мпк',
      },
      {
        name: 'Суздалец',
        bortNumber: '071',
        project: '1124М',
        type: 'малий протичовновий корабель',
        abbreviatedType: 'мпк',
      },
      {
        name: 'Муромец',
        bortNumber: '064',
        project: '1124М',
        type: 'малий протичовновий корабель',
        abbreviatedType: 'мпк',
      },
      {
        name: 'ТЛ-25',
        bortNumber: null,
        project: 'Р-376У',
        type: 'катер-торпедолов',
        abbreviatedType: 'катл',
      },
    ],
  },
  {
    name: '150 мінно-тральна тактична група',
    city: 'Севастополь',
    abbreviatedName: '150 мтг',
    ships: [
      {
        name: 'Иван Голубец',
        bortNumber: '911',
        project: '266М',
        type: 'морський тральщик',
        abbreviatedType: 'мтщ',
      },
      {
        name: 'Ковровец',
        bortNumber: '913',
        project: '266М',
        type: 'морський тральщик',
        abbreviatedType: 'мтщ',
      },
      {
        name: 'Иван Антонов',
        bortNumber: '601',
        project: '12700',
        type: 'морський тральщик',
        abbreviatedType: 'мтщ',
      },
      {
        name: 'Георгий курбатов',
        bortNumber: '631',
        project: '12700',
        type: 'морський тральщик',
        abbreviatedType: 'мтщ',
      },
      {
        name: 'Владимир Емельянов',
        bortNumber: '659',
        project: '12700',
        type: 'морський тральщик',
        abbreviatedType: 'мтщ',
      },
    ],
  },
  {
    name: '4 окрема бригада підводних човнів',
    city: 'Севастополь',
    abbreviatedName: '4 обрпч',
    ships: [
      {
        name: 'Алроса',
        bortNumber: '554',
        project: '877В',
        type: 'дизель-електричний підводний човен',
        abbreviatedType: 'депч',
      },
      {
        name: 'Ростов-на-Дону',
        bortNumber: 'Б-237',
        project: '636.3',
        type: 'дизель-електричний підводний човен',
        abbreviatedType: 'депч',
      },
      {
        name: 'Новоросійськ',
        bortNumber: 'Б-261',
        project: '636.3',
        type: 'дизель-електричний підводний човен',
        abbreviatedType: 'депч',
      },
      {
        name: 'Старий Оскол',
        bortNumber: 'Б-262',
        project: '636.3',
        type: 'дизель-електричний підводний човен',
        abbreviatedType: 'депч',
      },
      {
        name: 'Краснодар',
        bortNumber: 'Б-265',
        project: '636.3',
        type: 'дизель-електричний підводний човен',
        abbreviatedType: 'депч',
      },
      {
        name: 'Великий Новгород',
        bortNumber: 'Б-268',
        project: '636.3',
        type: 'дизель-електричний підводний човен',
        abbreviatedType: 'депч',
      },
      {
        name: 'Колпино',
        bortNumber: 'Б-271',
        project: '636.3',
        type: 'дизель-електричний підводний човен',
        abbreviatedType: 'депч',
      },
    ],
  },
  {
    name: '184 окрема бригада кораблів охорони водного району',
    city: 'Новоросійськ',
    abbreviatedName: '184 обоковр',
    ships: [],
  },
  {
    name: '181 дивізіон протичовнових кораблів',
    city: 'Новоросійськ',
    abbreviatedName: '181 днпк',
    ships: [
      {
        name: 'Касимов',
        bortNumber: '055',
        project: '1124М',
        type: 'малий протичовновий корабель',
        abbreviatedType: 'мпк',
      },
      {
        name: 'Ейськ',
        bortNumber: '054',
        project: '1124М',
        type: 'малий протичовновий корабель',
        abbreviatedType: 'мпк',
      },
    ],
  },
  {
    name: 'Окремий дивізіон патрульних кораблів',
    city: 'Новоросійськ',
    abbreviatedName: 'однпк',
    ships: [
      {
        name: 'Василий Быков',
        bortNumber: '368',
        project: '22160',
        type: 'патрульний корабель',
        abbreviatedType: 'пк',
      },
      {
        name: 'Дмитрий Рогачев',
        bortNumber: '357',
        project: '22160',
        type: 'патрульний корабель',
        abbreviatedType: 'пк',
      },
      {
        name: 'Павел Державин',
        bortNumber: '363',
        project: '22160',
        type: 'патрульний корабель',
        abbreviatedType: 'пк',
      },
    ],
  },
  {
    name: '170 дивізіон тральщиків',
    city: 'Новоросійськ',
    abbreviatedName: '170 днтщ',
    ships: [
      {
        name: 'Валентин Пикуль',
        bortNumber: '770',
        project: '266М',
        type: 'морський тральщик',
        abbreviatedType: 'мтщ',
      },
      {
        name: 'Железняков',
        bortNumber: '901',
        project: '12660',
        type: 'морський тральщик',
        abbreviatedType: 'мтщ',
      },
      {
        name: 'Вице-адмирал Захарьин',
        bortNumber: '908',
        project: '02668',
        type: 'морський тральщик',
        abbreviatedType: 'мтщ',
      },
    ],
  },
];
